# Cluster IP config for commands-depl
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: commandservice # must match deployment name
  ports:
  - name: commandservice # must match deployment name
    protocol: TCP
    port: 80
    targetPort: 80

# Can also put all of this into commands-depl.yaml file 
# but must put a new line with "---" before this