# Deployment of Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl

spec:
  replicas: 1 # instances (desired end state, changing number will change number of pods)

  # select template we're creating
  selector:
    matchLabels:
      app: commandservice

  # define pod and container we're going to use
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: chapinsmith/commandservice:latest
      # can ignore warnings about resource limits here for now
